### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by Ggmatch** [ykfe/dclone#4]
请问楼主，这个程序使用前需要先让github/gitlab添加本地主机的公钥吗？

**Comment by zhangyuang** [comment]
本质是调用git clone。自然是需要的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yifan <notifications@github.com&gt;
发送时间: 2020年6月27日 10:56
收件人: ykfe/dclone <dclone@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ykfe/dclone] 权限问题 (#4)
