### ISSUE TITLE
example 仓库代码优化建议

### ISSUE THREAD

**Issue by baxtergu** [ykfe/dclone#8]
这里可以加上 --depth=1 来加速克隆的速度，只 clone 最新的 commit hash 内容，历史忽略。
https://github.com/ykfe/dclone/blob/daf3eea1a3b107284501065fe434e1e51e22804d/src/dclone.ts#L22

另外，sparse-checkout 的这种方式有没有类似 clone --depth=1 的优化方案？
https://github.com/ykfe/dclone/blob/daf3eea1a3b107284501065fe434e1e51e22804d/src/dclone.ts#L50

**Comment by zhangyuang** [comment]
`depth=1`

可以来个 PR，不过 https://github.com/zhangyuang/create-ssr-app 最新的创建方式已经不使用 `dclone` 了

**Comment by baxtergu** [comment]
只有自定义模板的时候才会使用 dclone 了，这个修改影响应该不大，我有空提一个吧。

**Comment by baxtergu** [comment]
resolved https://github.com/ykfe/dclone/pull/9
